baseurl = "https://guitton.co/"
title = "Louis Guitton"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-140255752-1"

[params]
    author = "Louis Guitton"
    info = "Data Scientist at Onefootball and Freelance Software Engineer"
    description = "My personal serverless website"
    keywords = "blog,developer,personal"
    avatarurl = "images/louis.jpg"

    dateformat = "January 2, 2006"

    favicon_32 = "images/favicon.ico"
    favicon_16 = "images/favicon.ico"

    footercontent = "Enter a text here."

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = []

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/louisguitton"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/louisguitton"
[[params.social]]
    name = "Stackoverflow"
    icon = "fab fa-stack-overflow fa-2x"
    weight = 3
    url = "https://stackoverflow.com/users/3823815/louis-guitton"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 4
    url = "https://twitter.com/louis_guitton"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 5
    url = "https://linkedin.com/in/louisguitton/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 6
    url = "https://medium.com/@LaGuitteMH"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Contact me"
    weight = 3
    url = "/contact/"
